server:
  port: 8888
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/QuiqueTortosa/servicios_config
        #native:
        #  search-locations:
        #  - file:///c:\temp\config
        
        default-label: main
          
             